# Generated by Django 4.0.2 on 2022-05-11 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dutch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='English',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('dutchTranslation', models.ManyToManyField(to='learn.Dutch')),
            ],
        ),
        migrations.AddField(
            model_name='dutch',
            name='englishTranslation',
            field=models.ManyToManyField(to='learn.English'),
        ),
    ]
