# Generated by Django 4.0.2 on 2022-05-12 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dutch',
            name='englishTranslation',
        ),
        migrations.RemoveField(
            model_name='english',
            name='dutchTranslation',
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dutch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.dutch')),
                ('english', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.english')),
            ],
        ),
    ]
