# Generated by Django 4.0.2 on 2022-05-13 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_remove_dutch_englishtranslation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
