# Generated by Django 4.0.2 on 2022-05-16 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_translation_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='translation_key',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey> - <django.db.models.fields.related.ForeignKey>', max_length=203, unique=True),
        ),
        migrations.AlterField(
            model_name='dutch',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='english',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='dutch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='learn.dutch'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='english',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='learn.english'),
        ),
    ]
