# Generated by Django 4.0.2 on 2022-05-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_translation_translation_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='translation_key',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey> - <django.db.models.fields.related.ForeignKey>', max_length=203),
        ),
    ]
