# Generated by Django 4.0.2 on 2022-05-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_translation_translation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
