# Generated by Django 4.0.2 on 2022-05-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_alter_translation_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='translation_group',
            field=models.CharField(default='NA', max_length=50, unique=True),
        ),
    ]
